# Generated by Django 3.1.7 on 2021-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('default_code', models.TextField(default='', max_length=300, unique=True)),
                ('unique_name', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(upload_to='languages/icons')),
            ],
        ),
    ]
