# Generated by Django 3.1.7 on 2021-03-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='icon',
        ),
    ]
