# Generated by Django 3.1.7 on 2021-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_remove_language_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='default_code',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='language',
            name='unique_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
